package com.temenos.infinityassist.retail;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RetailScripts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public RetailScripts() {
	}

	public static void setRequestId(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			String response = (String) kcontext.getVariable("response");
			org.json.JSONObject responseJSON = new org.json.JSONObject(response);
			kcontext.setVariable("requestId",
					responseJSON.getString("requestId"));
		} catch (Exception e) {

		}
	}

}