package com.temenos.infinityassist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InfinityAssistScripts implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InfinityAssistScripts() {
    }

    
    public static void setErrorVariables(org.kie.api.runtime.process.ProcessContext kcontext){
        kcontext.setVariable("application", "Corporate");
        java.util.Map<String, Object> requestMap = new java.util.HashMap<String, Object>();
        if(kcontext.getVariable("AdditionalParameters") != null) {
	        requestMap  = (java.util.Map<String, Object>) kcontext.getVariable("AdditionalParameters");
        }
        //Request ID
        if(kcontext.getVariable("RequestId") != null) {
        	kcontext.setVariable("requestId", kcontext.getVariable("RequestId").toString());
        } else if(requestMap.get("requestId") != null) {
	        kcontext.setVariable("requestId", requestMap.get("requestId").toString());
        }
        
        //Facility ID
        if(kcontext.getVariable("FacilityId") != null) {
        	kcontext.setVariable("facilityId", kcontext.getVariable("FacilityId").toString());
        } else if(requestMap.get("facilityId") != null) {
        	kcontext.setVariable("facilityId", requestMap.get("facilityId").toString());
        }
        
        //Party ID
        if(kcontext.getVariable("PartyId") != null) {
        	kcontext.setVariable("partyId", kcontext .getVariable("PartyId").toString());
        } else if(requestMap.get("partyId") != null){
        	kcontext.setVariable("partyId", requestMap.get("partyId").toString());
        }
    }


}