package com.temenos.infinityassist.sme;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SMEScripts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public SMEScripts() {
	}

	public static void setRequestId(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			String response = (String) kcontext.getVariable("response");
			org.json.JSONObject responseJSON = new org.json.JSONObject(response);
			kcontext.setVariable("requestId",
					responseJSON.getString("requestId"));
		} catch (Exception e) {

		}
	}

	public static void checkSignedOfferLetter(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String documentResponse) {
		try {
			org.json.JSONObject documents = new org.json.JSONObject(
					documentResponse);
			org.json.JSONArray documentsArray = documents
					.getJSONArray("documents");
			if (documentsArray.length() > 0) {
				for (int index = 0; index < documentsArray.length(); index++) {
					org.json.JSONObject doc = documentsArray
							.getJSONObject(index);
					if (doc.get("documentType").equals("02")
							&& doc.get("documentStatus").equals("05")) {
						kcontext.setVariable("isSigned", true);
						break;
					} else {
						kcontext.setVariable("isSigned", false);
					}
				}
			} else {
				kcontext.setVariable("isSigned", false);
			}
		} catch (Exception e) {
			System.out.println("Exception: " + e.toString());
		}
	}

	public static void setParties(
			org.kie.api.runtime.process.ProcessContext kcontext,
			String relatedPartiesResponse) {
		try {
			org.json.JSONObject relatedParties = new org.json.JSONObject(
					relatedPartiesResponse);
			org.json.JSONArray relatedPartiesArray = relatedParties
					.getJSONArray("relatedParties");
			java.util.Set<String> prospectParties = new java.util.HashSet<>();
			java.util.Set<String> existingParties = new java.util.HashSet<>();
			for (int index = 0; index < relatedPartiesArray.length(); index++) {
				org.json.JSONObject party = relatedPartiesArray
						.getJSONObject(index);
				String partyId = party.getString("relatedPartyId");
				if (partyId.startsWith("NNVF")) {
					prospectParties.add(partyId);
				} else if (partyId.startsWith("ENVF")) {
					existingParties.add(partyId);
				}
			}
			kcontext.setVariable("prospectParties", prospectParties);
			kcontext.setVariable("existingParties", existingParties);
		} catch (Exception e) {

		}
	}
}
